### ISSUE TITLE
Retrieval issue for higher version on files that didn't change

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#127]
I'm fairly sure that this issue is with Figshare itself, but documenting it here for now.

Last month, I noticed an issue with retrieving a file for a v2 curation item. The file was not retrievable.

I suspect the problem has to do with the private ndownloader link, which works on v1 curation, but failed on v2.  I believe that if a file does not change, then the ndownloader links is no longer available as the file is public.

Because this was with a [real deposit](https://doi.org/10.25422/azu.data.12966581.v2), I needed to re-create it.  I did this on stage and first retrieve the v1 deposit:
```python
11:44:30 -     INFO: Total number of files: 4
11:44:30 -     INFO: Retrieving 1 of 4 : uaz_covid_testing_graph.png (191526)
11:44:30 -     INFO: URL: https://ndownloader.figsh.com/files/829557842
11:44:32 -     INFO: Retrieving 2 of 4 : uaz_covid_testing_data.csv (11694)
11:44:32 -     INFO: URL: https://ndownloader.figsh.com/files/829557844
11:44:33 -     INFO: Retrieving 3 of 4 : uaz_covid_testing_data.xlsx (146237)
11:44:33 -     INFO: URL: https://ndownloader.figsh.com/files/829557036
11:44:35 -     INFO: Retrieving 4 of 4 : README.txt (6758)
11:44:35 -     INFO: URL: https://ndownloader.figsh.com/files/829557032
```

Retrieval was done fine without any issues, as it should be.

After v1 retrieval and publishing, I updated the dataset in the same manner as I did for the public deposit, and tried again and received a HTTPError:
```python
12:05:45 -     INFO: Retrieving 1 of 5 : uaz_covid_testing_graph.png (191526)
12:05:45 -     INFO: URL: https://ndownloader.figsh.com/files/829557842
Traceback (most recent call last):
  File "ldcoolp/scripts/prereq_script", line 100, in <module>
    log=log, config_dict=config_dict)
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/main.py", line 144, in workflow
    pw.download_data()
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/main.py", line 101, in download_data
    log=self.log, url_open=self.url_open)
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/retrieve.py", line 87, in download_files
    token=fs.token, url_open=url_open)
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/retrieve.py", line 30, in private_file_retrieve
    urlretrieve(url, filename)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

With a simple try/except, I allow for it to proceed and you will see that other files are retrieve:
``` python
13:04:03 -     INFO: Total number of files: 5
13:04:03 -     INFO: Retrieving 1 of 5 : uaz_covid_testing_graph.png (191526)
13:04:03 -     INFO: URL: https://ndownloader.figsh.com/files/829557842
13:04:04 -  WARNING: Unable to retrieve /Users/cly/Downloads/curation/1.ToDo/Chun_Ly_6968970/v2/ORIGINAL_DATA/uaz_covid_testing_graph.png
13:04:04 -  WARNING: This is a bug with Figshare API
13:04:04 -     INFO: Retrieving 2 of 5 : uaz_covid_testing_data.csv (12309)
13:04:04 -     INFO: URL: https://ndownloader.figsh.com/files/829557848
13:04:05 -     INFO: Retrieving 3 of 5 : uaz_covid_testing_data.xlsx (94583)
13:04:05 -     INFO: URL: https://ndownloader.figsh.com/files/829557850
13:04:07 -     INFO: Retrieving 4 of 5 : records.zip (18690676)
13:04:07 -     INFO: URL: https://ndownloader.figsh.com/files/829557846
13:04:17 -     INFO: Retrieving 5 of 5 : README.txt (7216)
13:04:17 -     INFO: URL: https://ndownloader.figsh.com/files/829557852
13:04:18 -     INFO: Creating folder : /Users/cly/Downloads/curation/1.ToDo/Chun_Ly_6968970/v2/UAL_RDM
13:04:18 -     INFO: Saving ReDATA Curation Report to: /Users/cly/Downloads/curation/1.ToDo/Chun_Ly_6968970/v2/UAL_RDM
13:04:18 -     INFO: Saving as : ReDATA-DepositReview_Chun_Ly_6968970_v2.docx
13:04:21 -     INFO: Attempting to identify using article_id or curation_id ...
13:04:21 -     INFO: Unable to identify based on article_id or curation_id ...
13:04:21 -     INFO: Attempting to identify with name ...
```

**Comment by astrochun** [comment]
One way to fix this temporarily is to find the file that exists in previous version and copy it over.

**Comment by astrochun** [comment]
> One way to fix this temporarily is to find the file that exists in previous version and copy it over.

After some experimentation, it turned out that `curl -L` retrieves, the files, so the problem is in `urlretrieve` and how it handles a redirect to a public file.  It seems that not providing the token allows the redirect.  This is now rectified in 55f3dc7

**Comment by astrochun** [comment]
Not that this is related #32.  A quick tests show that the above fix also fix retrieval for a fully public dataset.
