### ISSUE TITLE
Bug: Qualtrics get_survey_responses fail with 500 response error

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#186]
**Describe the bug**
When attempting to retrieve data, a 500 error occurred.

**Reproduction Steps**
`get_data XXXXXXXX`

**Outputted Messages**
Traceback message:
```
Caught an HTTPError: 500 Server Error: Internal Server Error for url: https://uarizona.co1.qualtrics.com/API/v3/surveys/SV_39rs7lHGLUYFK7P/export-responses/ES_0HuX6bsqsiUHMKW
Body:
 {"meta":{"requestId":"2cdeac54-6119-4bb1-8c1b-54b4c7e0cc36","httpStatus":"500 - Internal Server Error","error":{"errorCode":"RTC_2","errorMessage":"Internal server error. Please contact Qualtrics support."}}}
Traceback (most recent call last):
  File "/home/curator/codes/LD_Cool_P/ldcoolp/scripts/prereq_script", line 100, in <module>
    log=log, config_dict=config_dict)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/main.py", line 151, in workflow
    q.retrieve_deposit_agreement(pw.dn.name_dict, browser=browser)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/api/qualtrics.py", line 266, in retrieve_deposit_agreement
    ResponseId = self.find_deposit_agreement(dn_dict)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/api/qualtrics.py", line 204, in find_deposit_agreement
    qualtrics_df = self.get_survey_responses(self.survey_id)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/api/qualtrics.py", line 164, in get_survey_responses
    check_response = issue_request("GET", check_url, headers=self.headers)
  File "/home/curator/codes/figshare/figshare/figshare.py", line 44, in issue_request
    response.raise_for_status()
  File "/opt/anaconda3/envs/curation/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: **https://uarizona.co1.qualtrics.com/API/v3/surveys/SV_39rs7lHGLUYFK7P/export-responses/ES_0HuX6bsqsiUHMKW**
```

**Version information**
- LD_Cool-P version: `0.17.6` 
[requirements.txt](https://github.com/ualibraries/LD_Cool_P/blob/v0.17.6/requirements.txt)

*Expected behavior*
Should have retrieved the Qualtrics responses. This is likely due to an issue with Qualtrics as it worked previously.

*Screenshots*

*Additional context*

**Implemented in**: N/A

**Comment by astrochun** [comment]
This issue was resolved on its own after the Qualtrics API did not give a 500 response error.
