### ISSUE TITLE
Error creating TinyURL link

### ISSUE THREAD

**Issue by zoidy** [ualibraries/LD_Cool_P#199]
Exception when creating README form TinyURL

```
21:55:31 -     INFO: TinyURL link does not exist. Creating!
21:55:31 -  WARNING: Caught an HTTPError: 400 Client Error: Bad Request for url: http://tinyurl.com/api-create.php?url=https://uarizona.co1.qualtrics.com/jfe/form/<snip>&alias=Abdolhosseini-14399315-1-README
--- Logging error ---
Traceback (most recent call last):
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/email/urls.py", line 56, in tiny_url
    response.raise_for_status()
  File "/home/curator/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://tinyurl.com/api-create.php?url=https://uarizona.co1.qualtrics.com/jfe/form/<snip>&alias=Abdolhosseini-14399315-1-README

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/curation/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/opt/anaconda3/envs/curation/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/opt/anaconda3/envs/curation/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/envs/curation/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/curator/codes/LD_Cool_P/ldcoolp/scripts/generate_qualtrics_links", line 101, in <module>
    readme_tinyurl = urls.tiny_url(readme_full_url, alias=readme_alias)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/email/urls.py", line 60, in tiny_url
    log.warning('Body:\n', response.text)
Message: 'Body:\n'
Arguments: ('Error',)
Traceback (most recent call last):
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/email/urls.py", line 56, in tiny_url
    response.raise_for_status()
  File "/home/curator/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://tinyurl.com/api-create.php?url=https://uarizona.co1.qualtrics.com/jfe/form/<snip>alias=Abdolhosseini-14399315-1-README

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curator/codes/LD_Cool_P/ldcoolp/scripts/generate_qualtrics_links", line 101, in <module>
    readme_tinyurl = urls.tiny_url(readme_full_url, alias=readme_alias)
  File "/home/curator/codes/LD_Cool_P/ldcoolp/curation/email/urls.py", line 61, in tiny_url
    raise HTTPError
requests.exceptions.HTTPError
```

**Comment by astrochun** [comment]
There is something wrong with parsing certain title it seems. I'm still looking into it. For now, use the full Qualtrics links, which seem to work.

**Comment by zoidy** [comment]
Thanks, I created the shortened link manually for now. This is a relatively low priority item since there is a manual workaround

**Comment by zoidy** [comment]
Can address w/ DigitalOcean + Wasabi alternative
