### ISSUE TITLE
Bug: Check for config file and provide warning if incorrect path provided

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#93]
**Describe the bug (REQUIRED)**

On occasion, the scripts do not run if an incorrect config file path is provided for `--config`:

**Reproduction Steps (REQUIRED)**
1. `python ldcoolp/scripts/get_curation_list --config config/blah.ini`

**Outputted Messages (REQUIRED)**

```python
Traceback (most recent call last):
  File "ldcoolp/scripts/get_curation_list", line 54, in <module>
    config.get('curation', 'log_parent_dir'))
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'curation'
```

**Version information (please complete the following, default in brackets): (REQUIRED)**
 - LD_Cool-P version: [e.g. `0.13.1`] 
 - ReQUIAM branch info: [e.g., `feature/logging`]
 - `pandas` version: 1.0.2
 - `requests` version: 2.22.0
 - `numpy` version: 1.17.4
 - `jinja2` version: 2.11.2

**Expected behavior (Optional)**
If file is not found, return a `FileNotFoundError`

**Comment by astrochun** [comment]
This will be part of `feature/logging` branch
