### ISSUE TITLE
Bug: UTF-8 handling by jinja2 for README file

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#95]
**Describe the bug (REQUIRED)**
Attempted to run prereq_script but it died on generating the README file based on the README file provided as a template.

**Reproduction Steps (REQUIRED)**
1. `python ldcoolp/scripts/prereq_script --config ldcoolp/config/<redacted_config>.ini --article_id XXXXXXXX`

**Outputted Messages (REQUIRED)**

```python 
Saving user template in DATA ...
Traceback (most recent call last):
  File "ldcoolp/scripts/prereq_script", line 63, in <module>
    browser=args.browser, config_dict=config_dict)
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/main.py", line 134, in workflow
    rc = ReadmeClass(pw.dn, curation_dict=config_dict['curation'])
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/inspection/readme/__init__.py", line 107, in __init__
    self.readme_template = self.import_template()
  File "/Users/cly/codes/UALibraries/LD_Cool_P/ldcoolp/curation/inspection/readme/__init__.py", line 167, in import_template
    jinja_template = env.get_template(self.readme_template)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Applications/anaconda3/envs/figshare/lib/python3.7/site-packages/jinja2/loaders.py", line 184, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 2771: invalid start byte
```

**Version information (please complete the following, default in brackets): (REQUIRED)**
 - LD_Cool-P version: 0.13.1 
 - ReQUIAM branch info: `feature/config_dict`
 - `pandas` version: 1.0.2
 - `requests` version: 2.22.0
 - `numpy` version: 1.17.4
 - `jinja2` version: 2.11.2

**Comment by astrochun** [comment]
This issue was due to the content provided and not a bug in the code.
